package net.cucumbersome.grottoleague.player

enum class Army(val displayName: String) {
    SPACE_MARINES("Space Marines"),
    ULTRAMARINES("Ultramarines"),
    IMPERIAL_FISTS("Imperial Fists"),
    DARK_ANGELS("Dark Angels"),
    BLOOD_ANGELS("Blood Angels"),
    SALAMANDERS ("Salamanders"),
    IRON_HANDS("Iron Hands"),
    SPACE_WOLVES("Space Wolves"),
    WHITE_SCARS("White Scars"),
    RAVEN_GUARD("Raven Guard"),
    DEATHWATCH("Deathwatch"),
    ELDAR("Eldar"),
    GREY_KNIGHTS("Grey Knights"),
    ASTRA_MILITARUM("Astra Militarum"),
    ADEPTA_SORORITAS("Adepta Sororitas"),
    ADEPTUS_CUSTODES("Adeptus Custodes"),
    ADEPTUS_MECHANICUS("Adeptus Mechanicus"),
    IMPERIAL_KNIGHTS("Imperial Knights"),
    CHAOS_SPACE_MARINES("Chaos Space Marines"),
    DEATH_GUARD("Death Guard"),
    THOUSAND_SONS("Thousand Sons"),
    WORLD_EATERS("World Eaters"),
    CHAOS_DAEMONS("Chaos Daemons"),
    CHAOS_KNIGHTS("Chaos Knights"),
    DRUKHARI("Drukhari"),
    HARLEQUINS("Harlequins"),
    YNNARI("Ynnari"),
    TYRANIDS("Tyranids"),
    GENESTEALER_CULTS("Genestealer Cults"),
    NECRONS("Necrons"),
    ORKS("Orks"),
    TAU_EMPIRE("T’au Empire"),
    LEAGUES_OF_VOTANN("Leagues of Votann")
}