# https://docs.github.com/en/actions

name: "Release"

on: # yamllint disable-line rule:true
  push:
    tags:
      - "**"

jobs:
  build-native-image:
    name: SpringBoot Native Application on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: sb3-native-image
            asset_name: sb3-native-image-linux-amd64
    steps:
      - uses: actions/checkout@v3

      - uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.1'
          java-version: '21'
          distribution: 'graalvm-community' # See 'Options' for all available distributions
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Build with gradle
        run: ./gradlew bootBuildImage

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}